services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  gateway:
    build: ./api_gateway
    command: python manage.py runserver 0.0.0.0:8000
    env_file: .env
    depends_on:
      - auth-service
      - painting-service
      - catalog-service
    ports:
      - "8000:8000"
    restart: always

  auth-service:
    build: ./auth_service
    command: python manage.py runserver 0.0.0.0:8000
    env_file: .env
    depends_on:
      - postgres
    restart: always

  painting-service:
    build: ./painting_service
    command: python manage.py runserver 0.0.0.0:8000
    env_file: .env
    depends_on:
      - postgres
      - image-processing-service
    restart: always

  catalog-service:
    build: ./catalog_service
    command: python manage.py runserver 0.0.0.0:8000
    env_file: .env
    depends_on:
      - postgres
    restart: always

  image-processing-service:
    build: ./image_processing_service
    command: python manage.py runserver 0.0.0.0:8000
    restart: always

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    restart: always

volumes:
  postgres_data:
