# Generated by Django 5.2.9 on 2025-12-14 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='MarkersSet',
            fields=[
                ('markers_set_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('colors_amount', models.IntegerField()),
                ('brand_name', models.CharField(max_length=255)),
                ('colors_data', models.JSONField()),
            ],
            options={
                'db_table': 'markers_sets',
            },
        ),
    ]
