# Generated by Django 5.2.9 on 2025-12-14 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Painting',
            fields=[
                ('painting_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_id', models.BigIntegerField()),
                ('photo', models.ImageField(upload_to='original/')),
                ('painting_numbered', models.ImageField(blank=True, null=True, upload_to='numbered/')),
                ('painting_colored', models.ImageField(blank=True, null=True, upload_to='colored/')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('category_id', models.IntegerField(blank=True, null=True)),
                ('is_public', models.BooleanField(default=False)),
                ('is_saved', models.BooleanField(default=False)),
                ('markers_set_id', models.IntegerField(blank=True, null=True)),
                ('colors_amount', models.IntegerField()),
                ('status', models.CharField(default='pending', max_length=32)),
            ],
            options={
                'db_table': 'paintings',
            },
        ),
    ]
